### ISSUE TITLE
'sanity' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ManishSongara** [basir/sanity-amazona#1]
![image](https://user-images.githubusercontent.com/31859160/165357077-a67d5b9e-2a4b-43cf-8d64-7ed85d81724d.png)

Try to start sanity, but it's giving following error...

**Comment by alexstouffer** [comment]
I had the same issue. Try using the command `npx sanity start`.

**Comment by ManishSongara** [comment]
you can also use:  npx @sanity/cli start
